### ISSUE TITLE
Allow SSL parameters for Net::HTTP to be configured

### ISSUE THREAD

**Issue by rsutphin** [NUARIG/castanet#5]
`Castanet::ServiceTicket`uses `Net::HTTP` for communication with the CAS server. When using SSL, it may be necessary (particularly in a testing environment) to specify an alternate CA. Allow this to be configured in somehow.

**Comment by hannahwhy** [comment]
How about this API:

``` ruby
class Client
  include Castanet::Client

  # keys in the hash map one-to-one to OpenSSL::SSL::SSLContext attributes
  def ssl_context
    { :ca_file => "...",
      ...
    }
  end

  def do_something
    # at this point, the client can propagate SSL context configuration to Net::HTTP instances
    st = service_ticket(ticket, service)
  end
end
```

`ssl_context` should return a map of some sort.  The name is a bit funny; I can see people trying to build `OpenSSL::SSL::SSLContext` instances from it and going "wtf does this not work?", but not sure how much of a problem that will be.

**Comment by rsutphin** [comment]
That looks reasonable to me. We would need to allow the SSL context parameters to be specified in an Aker configuration somehow and then propagated; that seems possible with this setup.

**Comment by hannahwhy** [comment]
I like this API more:

``` ruby
class Client
  include Castanet::Client

  # builds an SSL context object; I don't care what it is, but it must be
  # usable by Net::HTTP
  def ssl_context
  end
end
```

As far as I can tell, the SSL context should be opaque to castanet -- it shouldn't ever have to know its format or that `Net::HTTP` expects an `OpenSSL::SSL::SSLContext` instance.  Castanet just needs to know "this is an SSL context and this is how I tell `Net::HTTP` instances about it".

Unfortunately, this is complicated by the fact that the SSL extensions in `net/https` don't expose an `#ssl_context=` accessor -- `Net::HTTP` requires that you go through its SSL context accessors to set up an SSL context.  I'm not sure why -- as far as I can tell, allowing it to be directly set won't break anything.

Maybe I can monkeypatch that accessor in.

**Comment by rsutphin** [comment]
> As far as I can tell, the SSL context should be opaque to castanet -- it shouldn't ever have to know its format or that Net::HTTP expects an OpenSSL::SSL::SSLContext instance. Castanet just needs to know "this is an SSL context and this is how I tell Net::HTTP instances about it".

I don't agree with this. The fact that Castanet uses Net::HTTP is an implementation detail of Castanet. If Castanet starts using Typhoeus tomorrow, applications that use Castanet shouldn't have to change. It's reasonable to allow for configuration in a way that's easy to implement on top of Net::HTTP (as in your original suggestion), but if possible I'd avoid exposing an API which cements the use of Net::HTTP for ever and ever.

**Comment by rsutphin** [comment]
> I can see people trying to build OpenSSL::SSL::SSLContext instances from it and going "wtf does this not work?", but not sure how much of a problem that will be.

Also, I don't think this will be a problem. I don't think that people will have a prior expectation that they should produce an `OpenSSL::SSL::SSLContext`; they'll do whatever the documentation says to do.

**Comment by hannahwhy** [comment]
> I don't agree with this. The fact that Castanet uses Net::HTTP is an implementation detail of Castanet. If Castanet starts using Typhoeus tomorrow, applications that use Castanet shouldn't have to change. It's reasonable to allow for configuration in a way that's easy to implement on top of Net::HTTP (as in your original suggestion), but if possible I'd avoid exposing an API which cements the use of Net::HTTP for ever and ever.

Good point.  I wanted to avoid coding dependencies on Net::HTTP in Castanet, but that's really Castanet's responsibility, isn't it?

I'll go with the first API.
