### ISSUE TITLE
ServiceTicket#retrieve_pgt! does not fail if PGT retrieval fails

### ISSUE THREAD

**Issue by rsutphin** [NUARIG/castanet#6]
Contrary to the documentation, `ServiceTicket#retrieve_pgt!` does not only accept 200 responses from the proxy retriever. No matter the status, it sets `ServiceTicket#pgt` to the body of the response. It would be helpful if it raised an error immediately. The current behavior defers the failure until the first PT is requested.

**Comment by hannahwhy** [comment]
Yeah, I'm not sure where that 200 OK bit came from; there's no examples for failure cases, so I bet that has something to do with it.  I'll clarify the documentation in a few hours.

To make things clear: `#retrieve_pgt!` should only succeed if the response is 200; other responses should raise an exception (`Castanet::ProxyTicketError`, perhaps).

**Comment by rsutphin** [comment]
>  `#retrieve_pgt!` should only succeed if the response is 200; other responses should raise an exception (`Castanet::ProxyTicketError`, perhaps).

I agree.
